version: "3"

services:
  mongo:
    container_name: mongoose
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
  descomplica-api:
    container_name: graphql-api
    build:
      context: ./api/
      target: dev
    volumes:
      - .:/api
    command: >
      sh -c "npm run seed && npm run dev"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    env_file:
      - ./api/.env
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    depends_on:
      - mongo
