type Student {
  _id: ID!
  nome: String!
  cpf: String!
  email: String!
}

input StudentInput {
  nome: String!
  cpf: String!
  email: String!
}

type Query {
  students: [Student!]!
}

type Mutation {
  createStudent(data: StudentInput!): Student!
}
